function [methodinfo,structs,enuminfo,ThunkLibName]=usbPT104MFILE
%USBPT104MFILE Create structures to define interfaces found in 'UsbPt104Api'.

%This function was generated by loadlibrary.m parser version 1.1.6.37 on Wed Jun 25 12:17:48 2014
%perl options:'UsbPt104Api.i -outfile=usbPT104MFILE.m -thunkfile=USBPT104_thunk_pcwin64.c -header=UsbPt104Api.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'USBPT104_thunk_pcwin64');
% PICO_STATUS UsbPt104Enumerate ( char * details , unsigned long * length , COMMUNICATION_TYPE type ); 
fcns.thunkname{fcnNum}='uint32cstringvoidPtrCOMMUNICATION_TYPEThunk';fcns.name{fcnNum}='UsbPt104Enumerate'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'cstring', 'ulongPtr', 'enCommunicationType'};fcnNum=fcnNum+1;
% PICO_STATUS UsbPt104OpenUnit ( short * handle , char * serial ); 
fcns.thunkname{fcnNum}='uint32voidPtrcstringThunk';fcns.name{fcnNum}='UsbPt104OpenUnit'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'int16Ptr', 'cstring'};fcnNum=fcnNum+1;
% PICO_STATUS UsbPt104OpenUnitViaIp ( short * handle , char * serial , char * ipAddress ); 
fcns.thunkname{fcnNum}='uint32voidPtrcstringcstringThunk';fcns.name{fcnNum}='UsbPt104OpenUnitViaIp'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'int16Ptr', 'cstring', 'cstring'};fcnNum=fcnNum+1;
% PICO_STATUS UsbPt104CloseUnit ( short handle ); 
fcns.thunkname{fcnNum}='uint32int16Thunk';fcns.name{fcnNum}='UsbPt104CloseUnit'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'int16'};fcnNum=fcnNum+1;
% PICO_STATUS UsbPt104IpDetails ( short handle , short * enabled , char * ipaddress , unsigned short * length , unsigned short * listeningPort , IP_DETAILS_TYPE type ); 
fcns.thunkname{fcnNum}='uint32int16voidPtrcstringvoidPtrvoidPtrIP_DETAILS_TYPEThunk';fcns.name{fcnNum}='UsbPt104IpDetails'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'int16', 'int16Ptr', 'cstring', 'uint16Ptr', 'uint16Ptr', 'enIpDetailsType'};fcnNum=fcnNum+1;
% PICO_STATUS UsbPt104GetUnitInfo ( short handle , char * string , short stringLength , short * requiredSize , PICO_INFO info ); 
fcns.thunkname{fcnNum}='uint32int16cstringint16voidPtruint32Thunk';fcns.name{fcnNum}='UsbPt104GetUnitInfo'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'int16', 'cstring', 'int16', 'int16Ptr', 'uint32'};fcnNum=fcnNum+1;
% PICO_STATUS UsbPt104SetChannel ( short handle , USBPT104_CHANNELS channel , USBPT104_DATA_TYPES type , short noOfWires ); 
fcns.thunkname{fcnNum}='uint32int16USBPT104_CHANNELSUSBPT104_DATA_TYPESint16Thunk';fcns.name{fcnNum}='UsbPt104SetChannel'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'int16', 'enUsbPt104Channels', 'enUsbPt104DataType', 'int16'};fcnNum=fcnNum+1;
% PICO_STATUS UsbPt104SetMains ( short handle , unsigned short sixtyHertz ); 
fcns.thunkname{fcnNum}='uint32int16uint16Thunk';fcns.name{fcnNum}='UsbPt104SetMains'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'int16', 'uint16'};fcnNum=fcnNum+1;
% PICO_STATUS UsbPt104GetValue ( short handle , USBPT104_CHANNELS channel , long * value , short filtered ); 
fcns.thunkname{fcnNum}='uint32int16USBPT104_CHANNELSvoidPtrint16Thunk';fcns.name{fcnNum}='UsbPt104GetValue'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'int16', 'enUsbPt104Channels', 'longPtr', 'int16'};fcnNum=fcnNum+1;
enuminfo.enIpDetailsType=struct('IDT_GET',0,'IDT_SET',1);
enuminfo.enUsbPt104DataType=struct('USBPT104_OFF',0,'USBPT104_PT100',1,'USBPT104_PT1000',2,'USBPT104_RESISTANCE_TO_375R',3,'USBPT104_RESISTANCE_TO_10K',4,'USBPT104_DIFFERENTIAL_TO_115MV',5,'USBPT104_DIFFERENTIAL_TO_2500MV',6,'USBPT104_SINGLE_ENDED_TO_115MV',7,'USBPT104_SINGLE_ENDED_TO_2500MV',8,'USBPT104_MAX_DATA_TYPES',9);
enuminfo.enCommunicationType=struct('CT_USB',1,'CT_ETHERNET',2,'CT_ALL',4294967295);
enuminfo.enUsbPt104Channels=struct('USBPT104_CHANNEL_1',1,'USBPT104_CHANNEL_2',2,'USBPT104_CHANNEL_3',3,'USBPT104_CHANNEL_4',4,'USBPT104_CHANNEL_5',5,'USBPT104_CHANNEL_6',6,'USBPT104_CHANNEL_7',7,'USBPT104_CHANNEL_8',8,'USBPT104_MAX_CHANNELS',8);
methodinfo=fcns;