function [methodinfo,structs,enuminfo,ThunkLibName]=ps5000aWrapMFile
%PS5000AWRAPMFILE Create structures to define interfaces found in 'ps5000aWrap'.

%This function was generated by loadlibrary.m parser version 1.1.6.37 on Wed Jan 29 12:17:25 2014
%perl options:'ps5000aWrap.i -outfile=ps5000aWrapMFile.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
ThunkLibName=[];
% extern short _stdcall RunBlock ( short handle , long preTriggerSamples , long postTriggerSamples , unsigned long timebase , unsigned long segmentIndex ); 
fcns.name{fcnNum}='RunBlock'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16', 'long', 'long', 'ulong', 'ulong'};fcnNum=fcnNum+1;
% extern short _stdcall GetStreamingLatestValues ( short handle ); 
fcns.name{fcnNum}='GetStreamingLatestValues'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16'};fcnNum=fcnNum+1;
% extern unsigned long _stdcall AvailableData ( short handle , unsigned long * startIndex ); 
fcns.name{fcnNum}='AvailableData'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='ulong'; fcns.RHS{fcnNum}={'int16', 'ulongPtr'};fcnNum=fcnNum+1;
% extern short _stdcall AutoStopped ( short handle ); 
fcns.name{fcnNum}='AutoStopped'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16'};fcnNum=fcnNum+1;
% extern short _stdcall IsReady ( short handle ); 
fcns.name{fcnNum}='IsReady'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16'};fcnNum=fcnNum+1;
% extern short _stdcall IsTriggerReady ( short handle , unsigned long * triggeredAt ); 
fcns.name{fcnNum}='IsTriggerReady'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16', 'ulongPtr'};fcnNum=fcnNum+1;
% extern short  _stdcall ClearTriggerReady ( void ); 
fcns.name{fcnNum}='ClearTriggerReady'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% extern PICO_STATUS _stdcall SetTriggerConditions ( short handle , int * conditionsArray , short nConditions ); 
fcns.name{fcnNum}='SetTriggerConditions'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='ulong'; fcns.RHS{fcnNum}={'int16', 'int32Ptr', 'int16'};fcnNum=fcnNum+1;
% extern PICO_STATUS _stdcall SetTriggerProperties ( short handle , int * propertiesArray , short nProperties , long autoTrig ); 
fcns.name{fcnNum}='SetTriggerProperties'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='ulong'; fcns.RHS{fcnNum}={'int16', 'int32Ptr', 'int16', 'long'};fcnNum=fcnNum+1;
% extern PICO_STATUS _stdcall SetPulseWidthQualifier ( short handle , int * pwqConditionsArray , short nConditions , int direction , unsigned long lower , unsigned long upper , int type ); 
fcns.name{fcnNum}='SetPulseWidthQualifier'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='ulong'; fcns.RHS{fcnNum}={'int16', 'int32Ptr', 'int16', 'int32', 'ulong', 'ulong', 'int32'};fcnNum=fcnNum+1;
% extern void _stdcall setChannelCount ( short handle , short channelCount ); 
fcns.name{fcnNum}='setChannelCount'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int16', 'int16'};fcnNum=fcnNum+1;
% extern short _stdcall setEnabledChannels ( short handle , short * enabledChannels ); 
fcns.name{fcnNum}='setEnabledChannels'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16', 'int16Ptr'};fcnNum=fcnNum+1;
% extern short _stdcall setAppAndDriverBuffers ( short handle , short channel , short * appBuffer , short * driverBuffer , unsigned long bufferLength ); 
fcns.name{fcnNum}='setAppAndDriverBuffers'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16', 'int16', 'int16Ptr', 'int16Ptr', 'ulong'};fcnNum=fcnNum+1;
% extern short _stdcall setMaxMinAppAndDriverBuffers ( short handle , short channel , short * appMaxBuffer , short * appMinBuffer , short * driverMaxBuffer , short * driverMinBuffer , unsigned long bufferLength ); 
fcns.name{fcnNum}='setMaxMinAppAndDriverBuffers'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16', 'int16', 'int16Ptr', 'int16Ptr', 'int16Ptr', 'int16Ptr', 'ulong'};fcnNum=fcnNum+1;
methodinfo=fcns;